### ISSUE TITLE
No connection to SMTP-Server after upgrade to v0.60

### ISSUE THREAD

**Issue by psychofaktory** [ddavness/power-mailinabox#82]
Can't send or receive Mails anymore since upgrade to v0.60.

/var/log/mail.log says:
`Oct 18 10:27:28 mail postfix/smtpd[21610]: fatal: sqlite:/etc/postfix/noreply-addresses.cf: Can't open database: unable to open database file?
Oct 18 10:27:29 mail postfix/master[16689]: warning: process /usr/lib/postfix/sbin/smtpd pid 21610 exit status 1
Oct 18 10:27:29 mail postfix/master[16689]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
`

Also Roundcube says:
`Application Error (700): Addressbook source (carddav_2) not found!`

Already tried to run the upgrade setup a second time. But the errors are still there.

Operating System: Operating System: Ubuntu 20.04.5 LTS
noreply-adresses.cf looks like:
`dbpath=~/home/user-data/mail/users.sqlite
query = SELECT 'REJECT This address is not ready to receive email.' FROM noreply WHERE email='%s'
`

**Comment by psychofaktory** [comment]
Has it to do with this commit?
https://github.com/ddavness/power-mailinabox/commit/e1be9a5eeb6161b657fecc3ec7af87ce1084aeda#diff-63d2e75cb57b19001c6fcf8e09ee55a14880a751b25984261c6332481d87d4e9

**Comment by ddavness** [comment]
So update - it is indeed linked to that commit, but the problem seems to persist and the logs point to a configuration file that remained unchanged? I literally cannot pinpoint it.

**Comment by psychofaktory** [comment]
Maybe permissions has changed?

**Comment by ddavness** [comment]
Switched to testing on a staging machine - seems that for some reason the prod machine is acting up badly besides this issue.

**Comment by ddavness** [comment]
The commit I pushed should fix the issue on your end - the errors message I'm getting on my production machine seem to be suggesting something else is happening instead (they seem to be involving concurrency problems instead) and will investigate separately.

**Comment by psychofaktory** [comment]
Thanks for your investigations and the fix!

The error in Roundcube when filling in the To: field is still present.
`Application Error (700): Addressbook source (carddav_2) not found!`
However, contacts can be found via the existing address books.

It is still possible to send an e-mail if you answer an email.
But if I try to send a new e-mail I got the error:
`Verbindungsfehler (Fehler beim Erreichen des Servers)!`
